### ISSUE TITLE
Hearts being lost by naturaldeaths

### ISSUE THREAD

**Issue by Leothebeasty** [IkeVoodoo/LSSMP#11]
Hey, in the lifesteal smp. Natural causes dont lose you hearts, apparently when u die to natural causes, you lose hearts. I could do the give heart command but that wouldnt make it fun

**Comment by IkeVoodoo** [comment]
Yeah I know, it will be fixed with ver 1.6, just hold on for a bit!

**Comment by IkeVoodoo** [comment]
> When will the 1.6 update be out? Sometime today?

More like sometime in this month or a bit further, its such a huge update it takes a while!

**Comment by KushKaushik14** [comment]
ahhh please fix this. thankss !! 
otherwise the plugin is nicee

**Comment by IkeVoodoo** [comment]
I will, dw :D
