### ISSUE TITLE
how can i cahnge the heart recipe?

### ISSUE THREAD

**Issue by Turkyl** [IkeVoodoo/LSSMP#110]
i have a server where this plugin is here,and all the players,just need so many hearts,and how can i change it to be in middle a totem?thanks,have a nice day

**Comment by IkeVoodoo** [comment]
plugins/Lifesteal-Smp-Plugin/recipes/heartRecipe.json

**Comment by TheUnknown2000** [comment]
> plugins/Lifesteal-Smp-Plugin/recipes/heartRecipe.json

your talking about changing in aternos but i want to change it in my pc bcuz i have a different type of server

**Comment by TheUnknown2000** [comment]
> plugins/Lifesteal-Smp-Plugin/recipes/heartRecipe.json

how can i change it within the file
