### ISSUE TITLE
How to set max hearts

### ISSUE THREAD

**Issue by DaBlazePRO** [IkeVoodoo/LSSMP#111]
Just wondering how do i set max hearts someone can get, people have 200 hearts and i don't want that. Also what does  healthScale: 1.0
  scaleHealth: true

mean?

**Comment by IkeVoodoo** [comment]
Max health is coming in ver 1.6.5, healthScale is how many hearts should be removed/added, scaleHealth adds health to the killer (regens them) to the same percentage of health they where before, so if they kill someone while they are on full health. they will still be at full health without needing to regen
