### ISSUE TITLE
Replace ban with spectator mode

### ISSUE THREAD

**Issue by JindGH** [IkeVoodoo/LSSMP#112]
How can I replace the player getting banned when eliminated, to instead being put in gamemode spectator?

**Comment by JindGH** [comment]
I have should ban off and should spectate on but it still bans them:

elimination:
  spectate:
    killerDisconnected: '&cYour killer has disconnected!'
    shouldSpectate: true
    killerNotOnline: '&cYour killer is not online so you are not allowed to spectate!'
  bans:
    broadcastBan: false
    broadcastMessage: '&c%player% has lost all of it''s hearts and has been banned.'
    banMessage: '&cYou been banned due to loosing all of your hearts, your last killer
      was &4%player%'
    shouldBan: false
  shouldEliminate: true
  scaleHealth: true
  healthScale: 1.0
  environmentStealsHearts: false

**Comment by IkeVoodoo** [comment]
shouldBa: true

**Comment by JindGH** [comment]
> shouldBa: true

It still  bans them

**Comment by JindGH** [comment]
I want it to not ban them

**Comment by IkeVoodoo** [comment]
shouldBan: false
shouldSpectate: true

(in their correspective places)

**Comment by IkeVoodoo** [comment]
shouldBan: false
shouldSpectate: true

(in their correspective places)
