### ISSUE TITLE
recipe

### ISSUE THREAD

**Issue by TheUnknown2000** [IkeVoodoo/LSSMP#115]
i have the json ready but how do i replace it

**Comment by Riotiscool1089** [comment]
yeah me 2 i have no idea 
        "DTD",
        "TET",
        "DTD"
    ],
        "D": {
	    "item": "Minecraft:diamond_block
        },
        "E": {
            "item": "Minecraft:elytra"
        },
        "T": {
            "item": "minecraft:totem_of_undying"
        }
    }
}

i tried this but no work

**Comment by TheUnknown2000** [comment]
> yeah me 2 i have no idea "DTD", "TET", "DTD" ], "D": { "item": "Minecraft:diamond_block }, "E": { "item": "Minecraft:elytra" }, "T": { "item": "minecraft:totem_of_undying" } } }
> 
> i tried this but no work
