### ISSUE TITLE
Hello! I love the plugin but how do i make it so if they loose all their hearts they will be temporarily banned for 1 week.

### ISSUE THREAD

**Issue by ZERGOxXT12** [IkeVoodoo/LSSMP#116]

**Comment by ZERGOxXT12** [comment]
And i have another error.. When i join it also says this..
![image](https://user-images.githubusercontent.com/93690394/140241292-86911337-093f-40ee-8dd7-294e30e1b655.png)

**Comment by ZERGOxXT12** [comment]
And i also have another problem... so i changed the recipe to this

{
    "enabled": true,
    "shaped": true,
    "outputAmount": 1,
    "recipe": [
        "ODO",
        "DXD",
        "ODO"
    ],
    "items": {
        "O": {
            "item": "minecraft:obsidian"
        },
        "D": {
            "item": "minecraft:diamond_block"
        },
        "X": {
            "item": "minecraft:totem"
        }
    }
}

And it doesnt work.. even the old crafting recipe doesnt

**Comment by ZERGOxXT12** [comment]
And it says that the Life Steal plugin cant be enabled
![image](https://user-images.githubusercontent.com/93690394/140242443-63303776-8cdf-4440-ae11-17d6855028ac.png)

**Comment by IkeVoodoo** [comment]
Temp bans are coming in ver 1.6.5.0, Try updating the plugin to the latest version (1.6.4) and make sure you are running 1.17.1 (1.16.5 coming in next ver)
