### ISSUE TITLE
players hearts dont get removed when they dont die to players

### ISSUE THREAD

**Issue by festerexe** [IkeVoodoo/LSSMP#117]
players hearts dont get removed when they dont die to players. is this on purpose? or did i do something wrong

**Comment by IkeVoodoo** [comment]
environmentStealsHearts in the config

**Comment by cheikop** [comment]
> environmentStealsHearts in the config

I have the same problem, and I didn't understand what that meant.

**Comment by KasliEmre6292** [comment]
idk the config but i guess just change enviromentStealsHearts to true

**Comment by IkeVoodoo** [comment]
> > environmentStealsHearts in the config
> 
> I have the same problem, and I didn't understand what that meant.

Wops, sorry, you gotta change environmentStealsHearts to true in the config
