### ISSUE TITLE
How do I change Heart Recipe

### ISSUE THREAD

**Issue by Riotiscool1089** [IkeVoodoo/LSSMP#118]
I already know how to go into the heart recipe thing but I just really need to know how to set it up 

I have tried this but doesn't work

{
    "enabled": true,
    "shaped": true,
    "outputAmount": 1,
    "recipe": [
        "DTD",
        "TET",
        "DTD"
    ],
        "D": {
	    "item": "Minecraft:diamond_block
        },
        "E": {
            "item": "Minecraft:elytra"
        },
        "T": {
            "item": "minecraft:totem_of_undying"
        }
    }
}

**Comment by Riotiscool1089** [comment]
{
    "enabled": true,
    "shaped": true,
    "outputAmount": 1,
    "recipe": [
        "DWD",
        "TNT",
        "DTD"
    ],
        },
        "W": {
            "item": "Minecraft:wither_skeleton_skull"
        },
        "D": {
            "item": "Minecraft:diamond_block"
        },
        "T": {
            "item": "minecraft:totem_of_undying"
        },
        "N": {
            "item": "Minecraft:netherite_ingot"
}

**Comment by IkeVoodoo** [comment]
take the default heart recipe and just add to it, you removed a lot of needed things such as brackets, arrays etc, just reset it (delete it) and rewrite it, this time making sure you don't delete anything

**Comment by Riotiscool1089** [comment]
alr i'll try

**Comment by Riotiscool1089** [comment]
K, thank u it works :)
