### ISSUE TITLE
how do you comtomize the plugin on aternos?

### ISSUE THREAD

**Issue by JOshLaid** [IkeVoodoo/LSSMP#120]

**Comment by JOshLaid** [comment]
hoq to costomize the plugin on aternos

**Comment by IkeVoodoo** [comment]
wdym

**Comment by kristupas098** [comment]
its impossible

**Comment by Maks1116** [comment]
Did you mean `how to customize this plugin on aternos`?
If yes, than go to files, then `plugins`, then `Lifesteal-Smp-Plugin` and there you have configuration files for this plugin.
