### ISSUE TITLE
1.6.5

### ISSUE THREAD

**Issue by ole1011** [IkeVoodoo/LSSMP#123]
When does 1.6.5 come out?

**Comment by IkeVoodoo** [comment]
I am fighting a bug rn, then its done

**Comment by ole1011** [comment]
Nice

**Comment by IkeVoodoo** [comment]
And gotta finish a bit of things with translations

**Comment by ole1011** [comment]
Can i ask which translations? I mean do you have to translate everything or fix something?

**Comment by IkeVoodoo** [comment]
I have to fix some problems with the eliminations, and finish the translation handling so people can contribute their translations as well
