### ISSUE TITLE
hi! it would be good if you add non-op commands and features

### ISSUE THREAD

**Issue by ArspenWasTaken** [IkeVoodoo/LSSMP#124]
I have some idea abt non-op commands and features
command:
/lswithdraw  <player> <amount> will transfer command user's life to the other player
 /lstransit will convert command user's life into item form.
 
 feature:
enchanting effect to extra hearts so if the server have texture packs for hearts, we can know what's real and fake
add shouldspectatekiller in the files, the spectate killer feature is quite annoying because dead ppl cant go online when the killer is offline

these are my ideas, hope you'll add it in the future

**Comment by IkeVoodoo** [comment]
/lswithdraw is the same as /lstransit, it convert it to item form, I don't really have plans to add the transfer for hearts rn, I might reconsider tough, and yes i finally came around and added a custom model data to the item (931) to add textures and that option does sound interesting, ill give it a go! Just trying to get version 1.6.5 sorted then its releasing (problem with translations & eliminations)!

**Comment by ArspenWasTaken** [comment]
happy to hear that! I'm really excited for the new version bcs I'm planning to make a new season of our lifesteal server, I'll try to create a new command based on the plugin, can I do it and send the scripts if I complete it?
p/s it'll take some time if i make it bcs im not so good at java

**Comment by IkeVoodoo** [comment]
I am really bad at texturing/modelling, but ill try! (its fully customizable though, Going to make a disc for more specifics)
