### ISSUE TITLE
i cant craft the hearts

### ISSUE THREAD

**Issue by Lolking753** [IkeVoodoo/LSSMP#125]
i dont realy no but i think the crafting recepe i like in the video an i didnt work

**Comment by IkeVoodoo** [comment]
its not the same in the video, it is customizable however you'd need to know json, working on a better way to handle this, anyways its 4 obsidian in the corners and 4 diamond blocks next to the obsidian (leaving middle empty)

**Comment by 1-2039482-30** [comment]
What do i have to know in Json to change the crafting recipe?

**Comment by 1-2039482-30** [comment]
I'm willing to learn what i need to know

**Comment by IkeVoodoo** [comment]
plugins/LifeSteal-Smp-Plugin/recipes/heartRecipe.json

that's the json file, format is similar to mc's recipes

**Comment by TheUnknown2000** [comment]
> plugins/LifeSteal-Smp-Plugin/recipes/heartRecipe.json
> 
> that's the json file, format is similar to mc's recipes

i have the json but i cant change it using any software on my pc and i do not use aternos

**Comment by Soapy7261** [comment]
> its not the same in the video, it is customizable however you'd need to know json, working on a better way to handle this, anyways its 4 obsidian in the corners and 4 diamond blocks next to the obsidian (leaving middle empty)

Doesn't work for me, when I do that it just doesn't show up, I have confirmed the plugin is working and is installed
![doesntwork](https://user-images.githubusercontent.com/81933267/141211466-d6e6c11e-00b2-4ac9-a55f-d4a23c7b712f.png)

**Comment by IkeVoodoo** [comment]
Huh? Weird, send me the console logs (Please, use pastebin)

**Comment by Soapy7261** [comment]
> Huh? Weird, send me the console logs (Please, use pastebin)

Nevermind, i just went to do it and i made a heart, i guess i just needed to restart my server

**Comment by Soapy7261** [comment]
Update: if my server has been on for a while no one can craft hearts, I checked console but nothing was there.

**Comment by IkeVoodoo** [comment]
huh, weird

**Comment by Soapy7261** [comment]
> huh, weird

just went to boot up my server and got a error, https://pastebin.com/PT9WZwxW It ends up working just i just get this error on startup

**Comment by IkeVoodoo** [comment]
Yeah that issue if fixed in version 1.6.5

**Comment by TheUnknown2000** [comment]
> Yeah that issue if fixed in version 1.6.5

is there a way to use any software to change the recipe . or just give me the commmand in which right click a phantom membrage give 1 extra heart
