### ISSUE TITLE
Update Server is down/not responding

### ISSUE THREAD

**Issue by Greeenman999** [IkeVoodoo/LSSMP#127]
Dear IkeVoodoo, 

please make sure the Update Server is online, because my Console is spammed full of error messages, that the Update Server is down or remove the Auto Updater. 

Thanks a lot,
Greenman999

**Comment by IkeVoodoo** [comment]
Alright, Ill turn it on, btw in version 1.6.5 it should spawn not nearly as much as it does currently :D

**Comment by IkeVoodoo** [comment]
It's on

**Comment by Greeenman999** [comment]
Thanks
