### ISSUE TITLE
How to create custom heart recipe

### ISSUE THREAD

**Issue by 1-2039482-30** [IkeVoodoo/LSSMP#129]
How do i create a custom heart recipe?

**Comment by 1-2039482-30** [comment]
You said that I need to know json

**Comment by 1-2039482-30** [comment]
What do i have to know?

**Comment by IkeVoodoo** [comment]
plugns/LifeSteal-Smp-Plugin/recipes/heartRecipe.json

That's the JSON file, works similar to mc's default recipes

**Comment by 1-2039482-30** [comment]
Do i put this in the plugin section for the server?

**Comment by 1-2039482-30** [comment]
or where can i insert this file

**Comment by IkeVoodoo** [comment]
its already there, just edit it
