### ISSUE TITLE
Lifesteal commands not working

### ISSUE THREAD

**Issue by Faact** [IkeVoodoo/LSSMP#13]
I just downloaded the lifesteal plugin for 1.16.5 and works fine except for the commands. All of the commands are gone except the attribute one, attributing hearts works fine, the heart system works fine, but it's only the custom commands that don't work. Can you maybe help with this?

**Comment by 3ricbae** [comment]
its 1.17.1... also the attribute command is in base minecraft, not the plugin

**Comment by IkeVoodoo** [comment]
Also yeah, as above, it is 1.17.1, you cannot use it in 1.16.5, sorry!
