### ISSUE TITLE
Plugin keeps resetting after restart

### ISSUE THREAD

**Issue by Strandkoffer** [IkeVoodoo/LSSMP#131]
elimination:
  spectate:
    killerDisconnected: '&cYour killer has disconnected!'
    shouldSpectate: true
    killerNotOnline: '&cYour killer is not online so you are not allowed to spectate!'
  bans:
    broadcastBan: false
    broadcastMessage: '&c%player% has lost all of it''s hearts and has been banned.'
    banMessage: '&cYou been banned due to loosing all of your hearts, your last killer
      was &4%player%'
    shouldBan: false
  shouldEliminate: true
  scaleHealth: true
  healthScale: 1.0
  environmentStealsHearts: false
eliminated:
  cce327bf-ee19-46a3-ae69-6d6f2da71779: 571b2597-8cdf-4e1b-91c6-ca1120588e2b
  killers:
    571b2597-8cdf-4e1b-91c6-ca1120588e2b: !!java.util.UUID 'cce327bf-ee19-46a3-ae69-6d6f2da71779'

Its default config. I use /lsreload to make the changes to the config. But when I restart the server it says It failed to enable the plugin. Then it resets the config and I have to do lsreload to set the changes again

See my comment on ur plugin page btw

**Comment by IkeVoodoo** [comment]
Now i know what everyone's talking about, its crashing due to "!!java.util.UUID", i am going to fix that! Thank you for letting me know.
