### ISSUE TITLE
Issues with plugin!

### ISSUE THREAD

**Issue by M-u-i** [IkeVoodoo/LSSMP#136]
Whenever I start the server for the other file to configurate the plugin, this appears, and it doesn't make the file.

![image](https://user-images.githubusercontent.com/94337089/141785209-25ef9972-624f-4577-8d7d-62908c9069ae.png)

**Comment by M-u-i** [comment]
Just so you know I'm on Aternos, 1.16.5, and version 1.6.1.0.

**Comment by IkeVoodoo** [comment]
The plugin only works in 1.17.1 atm, you are also using an outdated version, and version 1.6.5 will bring 1.16.5 support

**Comment by M-u-i** [comment]
Oh, okay. Thank you for da answer!
