### ISSUE TITLE
Lifesteal Plugin Elimination Broken

### ISSUE THREAD

**Issue by ghost** [IkeVoodoo/LSSMP#137]
So the lifesteal plugin elimination is broken and every time I enable ban in config and reload it ingame it keeps on resetting and doesn't ban spectators. 
![image](https://user-images.githubusercontent.com/94396099/141834712-45044b74-69ef-48d2-b043-7e5b4b616db3.png)

**Comment by IkeVoodoo** [comment]
I am fighting with this issue from a while, its one of the top priority things! Also spectators don't get banned if you enable the shouldBan, they are just kept as spectators

**Comment by AfiqNurAiman** [comment]
when im set enviromentstealsheart to true, when i die it gave me hearts not dissapear
