### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by GamerDrLemon** [IkeVoodoo/LSSMP#138]
the console show up like this

```[13:22:11 WARN]: [LSSMP] Could not establish input stream to update server. Not an error, however if this persists make an issue at https://www.github.com/IkeVoodoo/LSSMP/Issues.
[13:27:12 WARN]: [LSSMP] Could not establish input stream to update server. Not an error, however if this persists make an issue at https://www.github.com/IkeVoodoo/LSSMP/Issues.
container@pterodactyl~ Server marked as offline...
[ULT8 Daemon]: Aborting automatic restart, crash detection is disabled for this instance.
```
and after that it not even restart

**Comment by IkeVoodoo** [comment]
thats weird, that error should almost never happen unless something crashed while the connection was establishing, I have no clue why its not restarting tho

**Comment by IkeVoodoo** [comment]
thats weird, that error should almost never happen unless something crashed while the connection was establishing, I have no clue why its not restarting tho
