### ISSUE TITLE
The plugin is not working

### ISSUE THREAD

**Issue by ader32d** [IkeVoodoo/LSSMP#14]
when my friend kill me or i kill him me or my friend dont get heart or get less heart

**Comment by IkeVoodoo** [comment]
Before reporting an issue, please use /pl or /plugins on your server to see if it is enabled

If the command /pl or /plugins is not recognized, you are not using a server software that allows for plugins
If the plugin shows up in red, that means it did not load correctly, ensure that you are using paper if you are please copy your whole console logs and upload them to pastebin, then send a link here.

I will try to help as soon as I can, however I am very busy right now so it may take a while to get a response.
