### ISSUE TITLE
Spectator mode after death all the time and TNT self TNT explosions don’t kill

### ISSUE THREAD

**Issue by ihatebrickplanet12** [IkeVoodoo/LSSMP#143]
when you blow yourself up, you gain a heart and don’t die but it shows the death screen and you don’t lose hearts if someone kills you. And whenever someone dies, even on more than 2 hearts, they are put in spectator.

**Comment by IkeVoodoo** [comment]
what version of the plugin do you have

**Comment by ihatebrickplanet12** [comment]
1.6.4.0

**Comment by IkeVoodoo** [comment]
weird

**Comment by ihatebrickplanet12** [comment]
does it have any effect about the fact my friends are cracked players?
Also for now I fixed the bigger issue with a repeating command block with /gamemode survival @a
