### ISSUE TITLE
add an option to change the heart's name in item form or add enchantment glint to it

### ISSUE THREAD

**Issue by ArspenWasTaken** [IkeVoodoo/LSSMP#144]
I'm having a little trouble in making a custom heart texture for my server, I tried to texture all the hearts with the name ❤ Extra heart. on it but it doesn't work with the symbol, can you add enchantment glint or add an option to change the heart's name? because if I made every red dye a heart it wouldn't be good ...

**Comment by IkeVoodoo** [comment]
Version 1.6.5 will add custom model data to the item so you can texture it with that
