### ISSUE TITLE
recipe doesn't work

### ISSUE THREAD

**Issue by stemmmmm** [IkeVoodoo/LSSMP#145]
{
    "enabled": true,
    "shaped": true,
    "outputAmount": 1,
    "recipe": [
        "ODO",
        "DFD",
        "ODO"
    ],
    "items": {
        "O": {
            "item": "minecraft:glass_bottle"
        },
        "D": {
            "item": "minecraft:red_dye"
        },
        "F": {
            "item": "minecraft:beacon"
        }
    }
}

**Comment by IkeVoodoo** [comment]
wdym with dosen't work
