### ISSUE TITLE
When I kill someone they don’t lose a great and I don’t gain one

### ISSUE THREAD

**Issue by Profire9** [IkeVoodoo/LSSMP#147]
I tried fixing it multiple times please help

**Comment by Profire9** [comment]
@IkeVoodoo i tried fixing it in the file manager but it did not work

**Comment by Profire9** [comment]
Oh shoot in the title heart autocorrected to great I meant heart

**Comment by IkeVoodoo** [comment]
What plugin are you using? Are you sure it's this one?

**Comment by Profire9** [comment]
Yes I am very certain it’s this one

**Comment by IkeVoodoo** [comment]
https://discord.gg/7hr8CxNEKk you can use $logs ConsoleLogs to send me your logs in the discord, also send me your config

**Comment by Profire9** [comment]
Actually it just started working I don’t know how but it did thank you anyway.
