### ISSUE TITLE
i cant craft heart

### ISSUE THREAD

**Issue by VexYonYT** [IkeVoodoo/LSSMP#148]
when i put the right item it wont craft it dooesent come a heart.

**Comment by IkeVoodoo** [comment]
Send me the console logs in a pastebin

**Comment by VexYonYT** [comment]
{
    "enabled": true,
    "shaped": true,
    "outputAmount": 1,
    "recipe": [
        "DTD",
        "TET",
        "DTD"
    ],
    "items": {
        "D": {
            "item": "minecraft:diamond_block"
        },
        "T": {
            "item": "minecraft:totem_of_undying"
        },
        "E": {
            "item": "minecraft:elytra"
        }
    }
}

**Comment by VexYonYT** [comment]
it says no problem but and it says enabeld but it doesent work to craft hearts but i can take hearts

**Comment by IkeVoodoo** [comment]
thats the heart recipe, i asked for the config

**Comment by VexYonYT** [comment]
elimination:
  spectate:
    killerDisconnected: '&cYour killer has disconnected!'
    shouldSpectate: true
    killerNotOnline: '&cYour killer is not online so you are not allowed to spectate!'
  bans:
    broadcastBan: false
    broadcastMessage: '&c%player% has lost all of it''s hearts and has been banned.'
    banMessage: '&cYou been banned due to loosing all of your hearts, your last killer
      was &4%player%'
    shouldBan: false
  shouldEliminate: true
  scaleHealth: true
  environmentStealsHearts: false
