### ISSUE TITLE
the plugin wont budge on aternos (wont work)

### ISSUE THREAD

**Issue by faultydevv** [IkeVoodoo/LSSMP#15]
alright so heres my problem, when i try to put it on aternos it could be paper or spigot i try always the earliest version, it cannot be enabled even though im using 1.17.1 paper/spigot i try older 1.17.1 versions and the commands ARE a thing and when i do /plugins the plugin appears in green as if it was enabled but when i die or kill someone or get killed nobody loses hearts its just all fine when i do /lsreaload or /lifestealreload it says in the chat: reloaded! still the same issue how can i exactly fix this?

**Comment by IkeVoodoo** [comment]
Hello! With the information you provided I do not have enough context to help you, here are a few steps you can take to give more info:

Start up the server, and kill your friend
Go to aternos.org/log while the server is online
Press the "Share" button (top right of the text)
Copy the link and send it here, I will reply as soon as possible!

**Comment by faultydevv** [comment]
hello i am sorry for not responding i have been busy all these days ill
look into that right now
