### ISSUE TITLE
I want to make it so when u get down to 1 heart and die u stay at 1 heart and the person who killed u dosnt gain a heart

### ISSUE THREAD

**Issue by TaaaapZ** [IkeVoodoo/LSSMP#155]
**Is your feature request related to a problem? Please describe.**
well i want people to still be able to play but have 1 heart so they are not banned and or in spectator mode

**Describe the solution you'd like**
for a code to be added to solve this solution/idea

**Describe alternatives you've considered**
im not a coder so i do not know how to code this into the game currently

**Comment by IkeVoodoo** [comment]
Set shouldBan to false in the config
--------------------------
Ciao da

Simone
--------------------------


Il giorno lun 29 nov 2021 alle ore 07:37 TaaaapZ ***@***.***>
ha scritto:

**Comment by IkeVoodoo** [comment]
wops, its shouldEliminate
--------------------------
Ciao da

Simone
--------------------------


Il giorno lun 29 nov 2021 alle ore 16:06 IkeVoodoo <
***@***.***> ha scritto:
