### ISSUE TITLE
How do I make it so that when someone dies for example from fall damage they still lose a heart?

### ISSUE THREAD

**Issue by vladimure** [IkeVoodoo/LSSMP#159]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vladimure** [comment]
I have set environmentStealsHearts to true and restarted the server several times and still doesnt work. I also tried switching the crafting recipe for the heart and doesnt work. If you have discord I would love to talk together and if u could help me.

**Comment by IkeVoodoo** [comment]
The discord is on the github page (just press "LSSMP" at the top of the
page to go there)
--------------------------
Ciao da

Simone
--------------------------


Il giorno mer 1 dic 2021 alle ore 17:06 vladimure ***@***.***>
ha scritto:
