### ISSUE TITLE
My feature request is due to me not understanding the commands for giving hearts to yourself or whomever you play with their respective hearts ex: /ls add Nish_yt 1. It is not working for me and only giving me the same response : Unknown command, use /help to gain a list of commands. Please help me,  I'm sorry to bother but if you see this issue please do respond

### ISSUE THREAD

**Issue by Nishwastaken** [IkeVoodoo/LSSMP#163]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nishwastaken** [comment]
I felt it would have worked off the bat I am using an aternos spigot server.
Is there a configuration I can edit? If so please tell me what to do

**Comment by IkeVoodoo** [comment]
If you don't have perms you get that message, If you don't have the plugin you get that message, easy enough
