### ISSUE TITLE
How do I get it to work on MInehut?

### ISSUE THREAD

**Issue by Orange64lol** [IkeVoodoo/LSSMP#17]
There is a server hosting site called MInehut and recently they added a feature to add your own custom plugins just by pulling the jar file into the plugins folder but its not working. It doesn't show up when I do /plugins

**Comment by IkeVoodoo** [comment]
Send me the console logs thank you!

**Comment by Orange64lol** [comment]
![logs](https://user-images.githubusercontent.com/89113967/129964291-8bf17cd5-9c57-4d67-8d9e-fefdfa30cf00.PNG)
Here is a picture of the server logs that I think are relating to the plugin issue. If you need more logs I can show you more.

**Comment by Orange64lol** [comment]
The server is on 1.17.1 by the way.

**Comment by IkeVoodoo** [comment]
Releasing version 1.6 today, you will be able to use it on spigot (as you are using spigot)
