### ISSUE TITLE
Exploding yourself puts you in  state where people can take your hearts but you don’t lose any

### ISSUE THREAD

**Issue by ihatebrickplanet12** [IkeVoodoo/LSSMP#175]
if you blow yourself up then you are in a state where people can kill you for hearts but you don’t lose any. To fix this remove the 1 heart heal when you gain a heart

**Comment by IkeVoodoo** [comment]
Weird, ill take a look into that

**Comment by ihatebrickplanet12** [comment]
scaleHealth: false fixed it
