### ISSUE TITLE
friend lost 2.5 hearts when I killed him. Shortly after, he died to a creeper but only lost one

### ISSUE THREAD

**Issue by ihatebrickplanet12** [IkeVoodoo/LSSMP#176]
I killed my friend, he lost 2.5 hearts. Then he died to a creeper but only lost 1. 

(I am using version 1.6.4.0 on a 1.17.1 server)

**Comment by IkeVoodoo** [comment]
hm weird, show me the config

**Comment by ihatebrickplanet12** [comment]
I use ploudos so I can’t send the file. I left it completely the same except I set environmentstealshearts to true and scaleHealth to false

**Comment by IkeVoodoo** [comment]
you can just copy-paste the config
