### ISSUE TITLE
[BUG] Dying sheeps with hearts

### ISSUE THREAD

**Issue by TypicalNameTag23** [IkeVoodoo/LSSMP#178]
**Bug**
You can use a heart to dye a sheep, consuming it without giving you a heart.

**Steps to reproduce**
Craft a heart and right click a sheep.

**Extra Info** 
You can use `SheepDyeWoolEvent` to prevent this. You can also rename hearts in an anvil.

**Comment by IkeVoodoo** [comment]
Thank you very much for the info!
