### ISSUE TITLE
[BUG] no main manifest attribute

### ISSUE THREAD

**Issue by wildpalms** [IkeVoodoo/LSSMP#179]
I am trying install the plugin on an oracle-linux instance 
I added the `lifesteal-smp-plugin-1.6.4.0.jar` file in /plugins directory
I ran the command `java -jar lifesteal-smp-plugin-1.6.4.0.jar`
I go the result: 

> no main manifest attribute, in lifesteal-smp-plugin-1.6.4.0.jar

Did I miss a step? or some dependency?

**Comment by wildpalms** [comment]
The install file was downloaded from Spigot

**Comment by IkeVoodoo** [comment]
This is not an installer, you need to put the jar file into the plugins folder on your server.
