### ISSUE TITLE
idk how to put it on aternos

### ISSUE THREAD

**Issue by RrOsz** [IkeVoodoo/LSSMP#18]
i download the plugin file from spigotmc but idk how to put it in aternos so can u pls help me

**Comment by IkeVoodoo** [comment]
It is already in their plugin repository, you do not need to download it from spigot if you are on aternos.

**Comment by RrOsz** [comment]
oh ok but my server is 1.16.5 will it work? and the what's the name of the plugin bcs i  searched it in aternos

**Comment by IkeVoodoo** [comment]
Nope 1.16.5 does not work, also it's name is "LifeSteal SMP Plugin" - Suggestion, update to 1.17.1
