### ISSUE TITLE
Annoying messages telling you about the new version

### ISSUE THREAD

**Issue by tpkowastaken** [IkeVoodoo/LSSMP#180]
Hi,
I have an issue with the messages telling me about the new version as they popup so often in the chat and it is quite annoying. Please add a value to config to disable those messages completely or just show them once after login (as most other plugins do). The perfect option would be to support auto-update but I can tell how hard that could be to implement. My temporary fix was to just rewrite the version in the jar file but, you're making new version so fast :}.

**Comment by IkeVoodoo** [comment]
Hello! Yes I do understand it can be annoying, I'll limit it to only log in and try to get auto-update working someday, what I suggest for now is you actually update rather than suppress the messages :D
