### ISSUE TITLE
How to revive a player after /lseliminate

### ISSUE THREAD

**Issue by Shrish-Saini** [IkeVoodoo/LSSMP#182]
I eliminated a player using /lseliminate but now i want to revive them back but /lsrevive isnt working.

**Comment by IkeVoodoo** [comment]
wdym

**Comment by Sil8ntPlays** [comment]
I died by a player and the revive command doesn't work to bring me back to life

**Comment by IkeVoodoo** [comment]
can you show me what you get in chat when you send the command?

**Comment by SpitfireWasTaken** [comment]
> wdym

Same issue here, it says "You cannot join this server, you are dead, your last killer was SpitfireBTW(my IGN)" when the person I /lseliminate 'd tries to join, and when I do /lsrevive it says "This person is not eliminated" I can't unban them using /pardon and can't really do nothing

**Comment by IkeVoodoo** [comment]
weird, ill look into it!

**Comment by IkeVoodoo** [comment]
Fixed
