### ISSUE TITLE
[BUG] can only change my hearts or the person running the command's hearts, no matter what name you put in

### ISSUE THREAD

**Issue by SpitfireWasTaken** [IkeVoodoo/LSSMP#183]
tried to do the /lshealth command, maybe not doing the add, but it works on me without the add part, when I try to do it to anyone else, it only changes my hearts, even if I put their IGN (e.g. "/lshealth PlayersIGN 10" it adds to my own hearts),  the way I go around this is opping the one that needs the hearts changed but that doesnt work anymore since a guy tried to give himself 1000 hearts when I opped him

**Comment by IkeVoodoo** [comment]
weird, ill look into it!
