### ISSUE TITLE
Config file glitching out 

### ISSUE THREAD

**Issue by Leonidariogamer** [IkeVoodoo/LSSMP#184]
So I recently updated the plugin and every time when someone leaves the games or someone's get killed and having still enough hearts sometimes the config file put them as eliminated when I choose the config file to not put eliminated it does not change anything please help
The config files I remove every time the eliminated players that are not eliminated 
![Screenshot_20220117-183904_Chrome](https://user-images.githubusercontent.com/87946642/149808135-b3654596-0685-431f-9ba3-d691c4ef5873.jpg)

**Comment by IkeVoodoo** [comment]
Upon changing the config you also have to do /lsreload or restart the server, I am unsure of why this is happening, seems like a bug

**Comment by IkeVoodoo** [comment]
Fixed
