### ISSUE TITLE
What happened was i was testing to see if the commands and everything were working for the server and then when i tested the eliminate command i eliminated myself. When i tried rejoining it said i was banned and couldnt join so i had a friend log on and revive me but after that it said I couldnt join because my killer wasnt on but i was the killer. If there's any way to fix this could you let me know thank you. Here are some screenshots[BUG]

### ISSUE THREAD

**Issue by tylerfern** [IkeVoodoo/LSSMP#185]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2022-01-17 115506](https://user-images.githubusercontent.com/37939128/149810359-afe77aa5-e6fc-4873-a86a-34971f077218.png)

**Additional context**

**Extra info**
Send a pastebin with the console logs, it helps a ton!

**Comment by tylerfern** [comment]
OOPS
WRONG PHOTO LOL

**Comment by tylerfern** [comment]
here is the correct one

**Comment by IkeVoodoo** [comment]
Go into the config and remove your ban, its a bug atm I am working on resolving it!

**Comment by tylerfern** [comment]
that worked tysm
