### ISSUE TITLE
I used the revive commanded and it did not work???

### ISSUE THREAD

**Issue by UltragamerYT** [IkeVoodoo/LSSMP#187]
So I was testing the lifesteal plugin and I killed my friend until when he lost his hearts then when I tried to revive him it did not work so I am not sure if it is a bug or something so please help me.

**Comment by IkeVoodoo** [comment]
Yeah its a bug

**Comment by UltragamerYT** [comment]
Is there a fix???

**Comment by romainhqpog** [comment]
I tested the command on myself but it kicked me and a i can't revive myself

**Comment by IkeVoodoo** [comment]
@UltragamerYT not yet

**Comment by IkeVoodoo** [comment]
Fixed
