### ISSUE TITLE
The NOTE section in the README conflict with the license (at least, i think)

### ISSUE THREAD

**Issue by JacksonChen666** [IkeVoodoo/LSSMP#188]
**DISCLAIMER: I am not a lawyer, this is not legal advice.**

The GNU GPL license is generally a license that restricts applying restrictions (i know, sounds odd. but it is what it is).

The [`NOTE` section of the README](https://github.com/IkeVoodoo/LSSMP#note) disallows redistribution unless explicitly permitted by the author, and also commercial use.
Unfortunately, the license actually *allows* doing such things, including private use, redistribution (source code must be available and accessible), AND commercial use.
It's not my claim, [it's based on the short notice in the LICENSE file visible on GitHub](https://github.com/IkeVoodoo/LSSMP/blob/master/LICENSE).
[![the license file of the project viewed on github](https://user-images.githubusercontent.com/50755746/151819980-1b5fb205-7af4-4088-a296-1d7b22103040.png)](https://github.com/IkeVoodoo/LSSMP/blob/master/LICENSE)

All in all, @IkeVoodoo should review the GPL v2 license and reconsider the [`NOTE` section of the README](https://github.com/IkeVoodoo/LSSMP#note).

**Comment by IkeVoodoo** [comment]
The note is just a note, not meant to be used to stop people, mostly discourage people from copying and pasting, however, thank you for telling me :D, if you have any suggestions for a license feel free to tell me!

**Comment by Makonede** [comment]
> The note is just a note, not meant to be used to stop people, mostly discourage people from copying and pasting, however, thank you for telling me :D, if you have any suggestions for a license feel free to tell me!

it is completely useless in its current state. the note does not and cannot discourage anything that is explicitly permitted by the GPLv3.

**Comment by JacksonChen666** [comment]
> if you have any suggestions for a license feel free to tell me!

Actually, the only way you can have that note (which is assumed to apply) and a license which doesn't conflict with that note is **not at all**, unless you cease to be "[open source](https://opensource.org/osd/)" or "[free software](https://www.gnu.org/philosophy/free-sw.en.html)" (free as in freedom, not gratis).

Both "Open source" and "Free software" *require* allowing redistribution and use, pretty much no matter what[^violate]. Your note forbids redistribution *unless* permitted, which is not "Open source" nor "Free software"

[^violate]: There's a very specific case where you're not allowed to use the software because you violated something in the license and you didn't correct it the violation, whatever, it's a bit of a mess to explain now but it is mostly "no matter what".

Unfortunately, the license you currently have is the GNU GPL v3, which is very much considered "free software" (https://www.gnu.org/licenses/license-list.html#GNUGPLv3). So I brought up this issue.

Again, not a lawyer, but there's some conflicts with that note and your license.

---

Also, another thing I noticed with your license, [the copyright notice ***for the license*** was replaced with yours](https://github.com/IkeVoodoo/LSSMP/commit/7aa27f59bb98ea009244cb0e5836abfcb10028b8#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7R4). That's not correct because *that copyright notice applies to the license document itself*.

You're not supposed to change the license document (and you're not allowed either), instead you should be [attaching copyright notices to your source code](https://github.com/IkeVoodoo/LSSMP/blob/7aa27f59bb98ea009244cb0e5836abfcb10028b8/LICENSE#L623-L650).

**Comment by Makonede** [comment]
@IkeVoodoo Please see #224.

**Comment by Makonede** [comment]
@JacksonChen666 fixed; you may close this issue
