### ISSUE TITLE
so i removed my and my friends heart and we got banned and when i put the rivive command it says it revives put it doesnt[BUG]

### ISSUE THREAD

**Issue by nomci** [IkeVoodoo/LSSMP#189]

**Comment by nomci** [comment]
when i got banned and i tried to revive using the revive command it dosent work

**Comment by IkeVoodoo** [comment]
That's a bug, thankfully I've fixed and I am probs releasing a new version today or very soon

**Comment by IkeVoodoo** [comment]
Fixed
