### ISSUE TITLE
Losing 2 hearts instead of 1 heart

### ISSUE THREAD

**Issue by ItzHozo** [IkeVoodoo/LSSMP#19]
I love this plugin, but can you make the default hearts that you lose when you die is 1, not 2? This would help me out a lot, and also does anyone know the custom craft for the hearts? Or even if their is a default recipe? If their isn't a default recipe it would be great if you made one!

**Comment by ItzHozo** [comment]
You also gain 2 hearts, is their anyway to change this?

**Comment by IkeVoodoo** [comment]
Send me the console logs otherwise I can't really help you!

**Comment by ItzHozo** [comment]
Thats fine! I fixed it, the person who was running the server had 2 lifesteal plugins, and they both worked at the same time, BUT is the craftable hearts only enabled once we make the recipe? Because if it is it might be better to change it to a default recipe like 8 diamond blocks and a totem or something.

**Comment by IkeVoodoo** [comment]
> Thats fine! I fixed it, the person who was running the server had 2 lifesteal plugins, and they both worked at the same time, BUT is the craftable hearts only enabled once we make the recipe? Because if it is it might be better to change it to a default recipe like 8 diamond blocks and a totem or something.

Recipe is coming in version 1.6 that should release today, hopefull!
