### ISSUE TITLE
Lifesteal Plugin Lags my Server

### ISSUE THREAD

**Issue by NotLily** [IkeVoodoo/LSSMP#195]
I'm using the newest Lifesteal plugin version of the lifesteal plugin and it's lagging my server even though it only has around 5 people online.
Server Specs
- Ryzen 5 3600
- 16 GB of ram

![image](https://user-images.githubusercontent.com/95505245/155656259-38ec87d8-4fc7-40f4-9c12-cdb6ce0e6dc1.png)

**Comment by IkeVoodoo** [comment]
This is known, i have fixed it just working on fixing a couple glitches and it will release

**Comment by NotLily** [comment]
Ok thanks!
