### ISSUE TITLE
totems take hearts?

### ISSUE THREAD

**Issue by BakkaXD** [IkeVoodoo/LSSMP#197]
i am running an smp with your plugin and it is going very well eccept 1 issue i just discovered
when i die with a totem the plugin removes a heart and i am unsure how to fix this

**Comment by IkeVoodoo** [comment]
Yes i know about this bug, its getting fixed next release

**Comment by BakkaXD** [comment]
Ahh thank you I think its got somthing to do with the way the plugin registers deaths maybe if there was a variable for totems or somthing not too sure

**Comment by BakkaXD** [comment]
I have found another issue you may know 
Players are loosing hearts to mobs and I have natural deaths disabled do you know the fix for this?

**Comment by IkeVoodoo** [comment]
join the discord, we have a fix there
