### ISSUE TITLE
accidently banned myself

### ISSUE THREAD

**Issue by hypixelsbgamer** [IkeVoodoo/LSSMP#198]
there doesn't seem to be a way to unban myself and I dont know if my friends can join or if my computers ip is public yet since they havent tested, how it happend I was testing some commands for this plugin added 700 hearts than did lseliminate did nothing so reset my hearts than elimenated and i cant log back on in my server

**Comment by IkeVoodoo** [comment]
go to namemc.com and paste in your name, then get your UUID and run /lsrevive youruuid
