### ISSUE TITLE
[suggestion] multiple ban time 

### ISSUE THREAD

**Issue by dryter97** [IkeVoodoo/LSSMP#199]
Pretty explaining itself. 
people there get ban for a precise amouth of time when getting fully lifestealed.

the goal is there is a long and short time for user.
more a player rankup different the bantime get. getting like a hardcore survival server with temporary ban.

the goal here is to reward the long time player with a lower ban time with an rankup system with permission related aside of lifesteal

**Comment by IkeVoodoo** [comment]
Interesting, I'll take a look into that

**Comment by dryter97** [comment]
i thought simply using permission with a configuration for every permission about them

maybe using like (pluginsname.bantime.group)

defining the group like you did in the configuration and voila. seam a interesting idea to me. people was requesting this kind of feature when i config but i dont know where to look for a good lifesteal plugins. so far its your the best.

**Comment by IkeVoodoo** [comment]
@dryter97 I updated the config to add something similar to the above, update to 2.3.18 and it will be there!
