### ISSUE TITLE
Life steal smp

### ISSUE THREAD

**Issue by Mantyzass** [IkeVoodoo/LSSMP#2]
hi for me life steal smp dont work i dont know why but i will send u my file 
[lifesteal-smp-plugin-1.5.1.1.zip](https://github.com/IkeVoodoo/LSSMP/files/6877010/lifesteal-smp-plugin-1.5.1.1.zip)

**Comment by Mantyzass** [comment]
and i use 1.17 version spigot/bukkit

**Comment by Mantyzass** [comment]
it says  Couldn't get pack info for: net.minecraft.server.packs.ResourceNotFoundException: 'pack.mcmeta' in ResourcePack './world/datapacks/lifesteal-smp-plugin-1.5.1.1.zip'

**Comment by IkeVoodoo** [comment]
> it says Couldn't get pack info for: net.minecraft.server.packs.ResourceNotFoundException: 'pack.mcmeta' in ResourcePack './world/datapacks/lifesteal-smp-plugin-1.5.1.1.zip'

This is a plugin, not a datapack, redownload it as a .jar file and put it in your server's plugin folder, if it still does not work seach up "how to setup a paper server and install plugins" on youtube

**Comment by Mantyzass** [comment]
can u make it work on aternos you need to sugestt  plugin
