### ISSUE TITLE
The Log Says An Error With Aternos

### ISSUE THREAD

**Issue by Percy-Venom** [IkeVoodoo/LSSMP#20]
I Use Aternos And It Shows A Red 1 On The Log. I Used Spigot And 1.17.1 And I Put Your Life Steal In Aternos' Plugins. When I Go To Log It Says This 
<img width="746" alt="Screenshot 2021-08-19 at 11 36 57 AM" src="https://user-images.githubusercontent.com/89181344/130016587-d7f62a8d-b24b-4d0e-aee3-a6fe3584b279.png">

Here Is The Link To The Log 
https://mclo.gs/6nSfccP

**Comment by IkeVoodoo** [comment]
Ah i see, you are using spigot, this plugin only works with paper for now, i will bring it to spigot as well on ver 1.6 (note: changing from spigot to paper won't break any of your plugins as long as they are made correctly, paper to spigot is what breaks them)

**Comment by Percy-Venom** [comment]
Oh Ok, Thank You For The Quick Reply.

**Comment by Percy-Venom** [comment]
Sorry For The Late Reply But The Mod Works Perfectly, I've Been Having Fun With My Friends For A While. Thanks For Making This Mod.
