### ISSUE TITLE
ERR: PlayerInteractEvent error

### ISSUE THREAD

**Issue by tiboorr** [IkeVoodoo/LSSMP#201]
Hello.
When i withdraw one hart and it gets intomy inventory, if i really quickly dubble right click it, it gives me 2 harts instead of one.
In console it says "[18:16:46 ERROR]: Could not pass event PlayerInteractEvent to LifeSteal-Smp-Plugin v1.0"
It's a lot longer error. if u want i can post it.

**Comment by IkeVoodoo** [comment]
Please post it to [Pastebin](https://pastebin.com/) and send the link here

**Comment by tiboorr** [comment]
i typed /lswithdraw then dubble clicked gart and it gave me 2 harts.
here is error https://pastebin.com/tJaW498M

**Comment by IkeVoodoo** [comment]
Version 2.3.18 has this issue fixed, thank you for reporting.
