### ISSUE TITLE
eliminated players can still join

### ISSUE THREAD

**Issue by nicogb2007** [IkeVoodoo/LSSMP#202]
When I have 0 heart left it kick me and say tat i'm eliminated
But i can join the server again and I have 1 heart 

https://user-images.githubusercontent.com/107760410/174442520-07e43ea4-2a2c-420e-88df-a6dbc7ad3008.mp4

**Comment by IkeVoodoo** [comment]
Should be fixed with 2.3.5, try it

**Comment by Adammca** [comment]
hello, I withdraw all my hearts and get eliminated and if i pt in console lsreset all it wont work how do i join on my server back + delete and install again does not work

**Comment by bendy1234** [comment]
> 

you need to run the command lsrevive not lsreset

**Comment by IkeVoodoo** [comment]
@nicogb2007 This issue is fixed in version 2.3.18 as far as I have seen.
