### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by dblblaster** [IkeVoodoo/LSSMP#209]
1. Bug? Stop dropping hearts when user is at minimum
    - I set up my server with 3 hearts minimum, I don't want the elimination+ban feature, they just need to suffer until they work their way up again. Problem is, they still drop hearts, so if they team up with someone then they could kill each other to infinitely farm hearts which would be game breaking.
2. Config option to entirely disable dropping hearts
3. Config option to disable the custom resource pack
4. Config option to disable beacon recipe (like when I don't use elimination+ban feature), the recipe becomes meaningless
5. Totem use from inventory doesn't seem to do anything, is this just a placeholder for something you'll add later?

**Comment by IkeVoodoo** [comment]
1. Will fix after rewrite
2. Will be added after rewrite
3. There is, check resourcepack.yml
4. beaconRecipe.yml there's "enabled" otherwise use the settings page of the recipe editor in game
5. It's mostly for compatibility with plugins that do that.

**Comment by dblblaster** [comment]
Cool, note that I managed to fix 1. myself, it's 2 lines of code, see #212

**Comment by IkeVoodoo** [comment]
@dblblaster This issue has been fixed, expect a plugin release soon!
