### ISSUE TITLE
I cant get my server to work with lifesteal plugin 

### ISSUE THREAD

**Issue by OMEGALUL3** [IkeVoodoo/LSSMP#21]
It gives me an error in the log on aternos. It states the plugin lifesteal smp couldnt be enabled i would appreciate if i got help as soon as possible as i have the smp launching in about 2 days. I would promote you in the server description too.
help is needed asap.

**Comment by IkeVoodoo** [comment]
Yes can you send me the console logs? Thank you!

**Comment by OMEGALUL3** [comment]
[
![Log _ Aternos _ Free Minecraft Server - Google Chrome 8_20_2021 7_49_52 AM (2)](https://user-images.githubusercontent.com/89186848/130169108-cff5b7fa-20c5-4b82-b551-ae83db006427.jpg)
](url)[
![Log _ Aternos _ Free Minecraft Server - Google Chrome 8_20_2021 7_52_41 AM (2)](https://user-images.githubusercontent.com/89186848/130169317-8cc6ff35-0020-4c69-9cc3-1438f5502ac9.png)
](url) there you go

**Comment by OMEGALUL3** [comment]
My server is running on 1.17.1 i sacrificed everything for this i wanted my players to have access to duping in 1.17 but I dumped it for lifesteal i am counting on you. You are my last hope

**Comment by OMEGALUL3** [comment]
Also I am running on SpigotMC

**Comment by OMEGALUL3** [comment]
it works but i killed my player and now he cant respawn he lost all his heartswhat do i do?

**Comment by OMEGALUL3** [comment]
also i think there is a bug as we are losing hearts on fall damage and mob deaths too

**Comment by adi-roxx11** [comment]
@OMEGALUL3  could you help me get it to work please

**Comment by adi-roxx11** [comment]
@OMEGALUL3  i think the reason for that is the environment  steals hearts is set to true

**Comment by adi-roxx11** [comment]
How do i fix this 
<img width="1093" alt="Screenshot 2021-08-20 at 10 20 22 AM" src="https://user-images.githubusercontent.com/63908834/130180811-f6546b08-9a52-4141-a1c6-c6395a0e46fc.png">

**Comment by adi-roxx11** [comment]
https://mclo.gs/DHivYDa
My LOGS

**Comment by OMEGALUL3** [comment]
use paper

**Comment by OMEGALUL3** [comment]
it worked for me

**Comment by OMEGALUL3** [comment]
> also i think there is a bug as we are losing hearts on fall damage and mob deaths too

how do i fix this

**Comment by adi-roxx11** [comment]
Go to the config files which are located in the plugin and change environmental steal harts to false

**Comment by OMEGALUL3** [comment]
> Go to the config files which are located in the plugin and change environmental steal harts to false

i am trying rn

**Comment by adi-roxx11** [comment]
should i reinstall  the plugin once i enable it on paper

**Comment by OMEGALUL3** [comment]
> should i reinstall the plugin once i enable it on paper

yessir

**Comment by adi-roxx11** [comment]
did it work

**Comment by OMEGALUL3** [comment]
i checked and environment steals heart is et to false

**Comment by adi-roxx11** [comment]
wait this plugin might be from the one parrot created in which your ake damage from mobs and environment as well

**Comment by adi-roxx11** [comment]
it might be from this series instead the original  one https://www.youtube.com/watch?v=jCcdqeXGNTE

**Comment by OMEGALUL3** [comment]
then how do i change it

**Comment by OMEGALUL3** [comment]
[
![Log _ Aternos _ Free Minecraft Server - Google Chrome 8_20_2021 7_52_41 AM (2)](https://user-images.githubusercontent.com/89186848/130181694-469a4702-5cdb-4aef-926b-600139d2fe77.png)
](url)

**Comment by adi-roxx11** [comment]
can you steal lives
once you enter the server

**Comment by OMEGALUL3** [comment]
pls help

**Comment by OMEGALUL3** [comment]
> can you steal lives
> once you enter the server

yes i can

**Comment by OMEGALUL3** [comment]
> > can you steal lives
> > once you enter the server
> 
> yes i can

but i lose lives when i die from mobs too

**Comment by adi-roxx11** [comment]
This is a feature programmed from the dev

**Comment by adi-roxx11** [comment]
You might need to cantact them to get this changed

**Comment by OMEGALUL3** [comment]
> You might need to cantact them to get this changed

is it possible to contact parrot himself?

**Comment by adi-roxx11** [comment]
parrotxbiz@gmail.com
--

**Comment by OMEGALUL3** [comment]
thanks your an angel

**Comment by adi-roxx11** [comment]
Know this he is running a huge channel and also is working on his series

**Comment by OMEGALUL3** [comment]
> Know this he is running a huge channel and also is working on his series

yes i know but will he link me the plugin i mean is it legal

**Comment by adi-roxx11** [comment]
it should be

**Comment by OMEGALUL3** [comment]
ok

**Comment by IkeVoodoo** [comment]
> Also I am running on SpigotMC

It runs only on paper for now, however version 1.6 should release today and will allow you to use paper!

**Comment by adi-roxx11** [comment]
will version 1.6 also have crafting of hearts

**Comment by OMEGALUL3** [comment]
> > Also I am running on SpigotMC
> 
> It runs only on paper for now, however version 1.6 should release today and will allow you to use spigot!

1.6 really needs heart crafting it's lacking rn

**Comment by IkeVoodoo** [comment]
@adi-roxx11 @OMEGALUL3 Yes, ineed, it will have crafting, I am making it as I am writing this.

**Comment by OMEGALUL3** [comment]
> @adi-roxx11 @OMEGALUL3 Yes, ineed, it will have crafting, I am making it as I am writing this.

Thanks your an angel how much estimated time left until release on aternos?

**Comment by IkeVoodoo** [comment]
> > @adi-roxx11 @OMEGALUL3 Yes, ineed, it will have crafting, I am making it as I am writing this.
> 
> Thanks your an angel how much estimated time left until release on aternos?

The release will be on spigotmc, aternos will update accordingly, I am not in control of when they update, however should be relatively soon after i release it, rn i am working on the recipe file and loading it!

**Comment by OMEGALUL3** [comment]
Please try to make the ingredients for recipe Rare but not very rare so that it's easily craftable but still not common

**Comment by IkeVoodoo** [comment]
> Please try to make the ingredients for recipe Rare but not very rare so that it's easily craftable but still not common

Hello! Rn it requires 4 diamond blocks and 4 obsidian, however it is configurable in the config, oh also I updated

**Comment by OMEGALUL3** [comment]
hey i was looking through server files and somehow somewhy i dont see a folder for the config file there is just the 1.6 alpha jar file i think i need assistance

**Comment by OMEGALUL3** [comment]
[
![Files _ Aternos _ Free Minecraft Server - Google Chrome 8_21_2021 7_49_51 AM (2)](https://user-images.githubusercontent.com/89186848/130307563-f584e578-7944-467a-a4a3-9c486078bd24.png)
](url)

**Comment by OMEGALUL3** [comment]
do one thing share me the title of the folder that was supposed to be there and share me the contents of the folder too which were the config i will perform the download manually

**Comment by OMEGALUL3** [comment]
i solved it but its very laggy try to lighten the string and code

**Comment by adi-roxx11** [comment]
@OMEGALUL3  whats the crafting recipe for hearts

**Comment by OMEGALUL3** [comment]
ii dont know

**Comment by IkeVoodoo** [comment]
> i solved it but its very laggy try to lighten the string and code

The plugin is very fast, it is not my fault if the server is laggy, if you are using an outdated version, update.

**Comment by adi-roxx11** [comment]
The solution i found for the lag was to use paper 1.17.1 instead of Spigot 1.17.1 and also if you see your plugin files there is actually quiet a lot of them which you might have to remove

**Comment by adi-roxx11** [comment]
this plugin works on the server RAM and since there quiet a lot it is overloading the server think of it as an laptop with too many games open it lags it

**Comment by IkeVoodoo** [comment]
Please, please please, inform yourself before making claims, the amount of files in the plugin is actually very little, and every app uses the ram, I don't understand your point?
