### ISSUE TITLE
How do you craft hearts?

### ISSUE THREAD

**Issue by JacksonJukes** [IkeVoodoo/LSSMP#22]
I started a smp bases around this plugin and after about an hour we realized the 2 people that died to mobs had lost hearts. I'm trying to figure out how to craft hearts so I can tell them and they can get some hearts back.

**Comment by IkeVoodoo** [comment]
Hello! So dying to mobs now is an option you have to turn on for it to work so you'll be glad to hear that, anyways to craft hearts by default is 4 obsidian in the corners, 4 diamond blocks next to the obsidian to form something like a furnace, however if you want to change it simply go to:

plugins/LifeSteal-Smp-Plugin/recipes/

there should be a .json file, open that up and edit the contents inside of Recipe, each character is one slot, spaces are empty slots, so say you'd have

ODO
D O
ODO

(Default recipe)

O - obsidian
D - diamond_block

inside of the items tag you can add like

"O": {
   "item": "minecraft:obsidian"
}

which will tell the plugin "hey here O is obsidian" and in that specific slot there is gonna be an obsidian block! (Sorry if the explanation was bad)

**Comment by JacksonJukes** [comment]
Thanks!

**Comment by IkeVoodoo** [comment]
> Btw I don’t really know how to edit/write code but is that the only way to make it so you only lose hearts from players?

there is an option in the config which works as of 1.6

**Comment by oofboi44** [comment]
hi! i have the recipe open, but even when i try to craft it, it doesnt work. i am using 1.17, and its on a minehut server. is there something that i am doing wrong?

**Comment by IkeVoodoo** [comment]
Can you send me the recipe .json file? Thank you!

**Comment by oofboi44** [comment]
sorry for the late reply, Github doesn't support .json files, so I will just copy the text here

{
    "enabled": true,
    "shaped": true,
    "outputAmount": 2,
    "recipe": [
        "ODO",
        "D D",
        "ODO"
    ],
    "items": {
        "O": {
            "item": "minecraft:obsidian"
        },
        "D": {
            "item": "minecraft:diamond_block"
        }
    }
}

**Comment by oofboi44** [comment]
when I put it in the table, nothing happens

**Comment by IkeVoodoo** [comment]
> /lsreload to reload

After you changed recipe, do this, it will reload the recipe

**Comment by oofboi44** [comment]
hi! again, sorry for the late reply, but when I reloaded it, it still doesn't work. also, if the  crafting recipe doesn't work, its np

**Comment by benstr101** [comment]
Is there another way I can customize the recipe? It says that the site is blocks. Thanks

**Comment by IkeVoodoo** [comment]
Your JSON is invalid,

**Comment by scrubdapoopydank** [comment]
hi pls help me 
i want to craft heart with netherite and obsidian and totem. i want to keep the same order as u but replace diamond with netherite block and with totem in middle and obsidian. basically the order u have but with totem in middle. pls give me code

**Comment by IkeVoodoo** [comment]
The above screenshot works, however the json is broken, that is why as of 1.6.5 i will add a json fixer when loading the json! (it is missing two ending curly brackets at the bottom)

**Comment by scrubdapoopydank** [comment]
ok thx

**Comment by IkeVoodoo** [comment]
also, to replace the diamond block with netherite block, just change "diamond_block" to "netherite_block" in the recipe

**Comment by scrubdapoopydank** [comment]
can u type it out so i can copy and paste pls

**Comment by pinkpenguin2** [comment]
how do you revive
soemone i got locked out of my sever

**Comment by pinkpenguin2** [comment]
@IkeVoodoo 
psl help i have modrate my sever

**Comment by Potatokuun** [comment]
Hi @IkeVoodoo, could you tell me how to turn on the dying to mobs option so that players loses hearts when they die to mobs too ?
