### ISSUE TITLE
When a player dies it says "spectate world" or "title screen"

### ISSUE THREAD

**Issue by JerichoTorrent** [IkeVoodoo/LSSMP#230]
Basically the title. Gamemode is set to survival so I'm not sure why it would say this. For context the server _used_ to be a hardcore world, but I'm not sure why it would still act like that on survival. When you click "spectate world" you actually just respawn like normal.

**Comment by IkeVoodoo** [comment]
That's weird, I've never encountered an issue like that, may you share your server logs?

**Comment by JerichoTorrent** [comment]
> That's weird, I've never encountered an issue like that, may you share your server logs?

Erm, so it kinda fixed itself when I made a new world using MyWorlds, and made it my level-name (the main world). I believe it was because the world was first created in hardcore mode, then changing it back to survival, in combination with LSSMP, caused some weird unfortunate series of events. Can't say for sure, but the issue is fixed.
