### ISSUE TITLE
Mobs

### ISSUE THREAD

**Issue by Anay5499** [IkeVoodoo/LSSMP#25]
I belive you said you can turn off losing hearts to mobs? how do i do that what is the command to do that also is there a way i can withdraw hearts for example if i wanted to give someone a heart but i dont want to die because i would lose all my levels can i somehow withdraw a heart item?

**Comment by IkeVoodoo** [comment]
plugin/LifeSteal-Smp-Plugin/config.yml

inside of that file there is a "environmentStealsHearts", that is loosing hearts to mobs/fall damage/lava etc

to add hearts do:

/lshealth add PlayerName AmountOfHeartsInNumbers

to remove:

/lshealth remove PlayerName AmountOfHeartsInNumbers

example:

/lshealth add IkeVoodoo 1

Adds one heart

**Comment by Anay5499** [comment]
so there is no way to withdraw 1 of my hearts and give it to one of my friend out of MY health bar without using op

**Comment by IkeVoodoo** [comment]
Get him to kill you? idk what you are talking about really

**Comment by IkeVoodoo** [comment]
Well i mean not yet, i might add an item for that tho! (or use the commands from console)
