### ISSUE TITLE
1.6

### ISSUE THREAD

**Issue by Anay5499** [IkeVoodoo/LSSMP#26]
I added the latest version to aternos the alpha 1.6 and the server takes SO long to start and once it starts its VERY laggy it doesn't load chunks and if u disconnect and try to rejoin it won't let you it will say timed out and when you check the people online the server your username is also there even though u already disconnected is there any way I can fix this?
should i send the console there is A LOT of errors and then it says DO NOT REPORT TO PAPER also i would like to say the previous versions of this plugin were working just fine its just the latest one

**Comment by IkeVoodoo** [comment]
Yeah i know this error, i am trying to fix it (What the hell could be causing it?)

**Comment by IkeVoodoo** [comment]
Fixed in 1.6.1
