### ISSUE TITLE
Not removing hearts

### ISSUE THREAD

**Issue by Nameless-Guy** [IkeVoodoo/LSSMP#28]
I hav the plugin installed with via version and via rewqind and its not removing my hearts

**Comment by IkeVoodoo** [comment]
Send me console logs (please make a pastebin)

**Comment by Nameless-Guy** [comment]
i had older version of plugin
i found that it updated a few hours after i installed it
can you tell me how i can change recipe of craftable heart coz its tooo easy to craft if you hav dias
i am thingking of replacing the obby with 2 golden apples and 2 golden carrots and a totem in mid

**Comment by IkeVoodoo** [comment]
plugins/LifeSteal-Smp-Plugin/recipes

there is a .json file in that, how to change:

inside "recipes" there is the shape of the crafting, each character represents a slot, spaces represent empty slots

inside "items" is a list of which character corresponds to what item, so for example

"G": {
    "item": "minecraft:golden_apple"
}

will mean that when you put "G" inside "recipe" it will know that in that slot a golden apple has to go there

**Comment by Nameless-Guy** [comment]
@IkeVoodoo can you add my discord @NamelessGuy#2377
it will be easier to communicate

**Comment by Nameless-Guy** [comment]
the thing is that if i save the crafting table it jus resets when i restart server

**Comment by IkeVoodoo** [comment]
> the thing is that if i save the crafting table it jus resets when i restart server

Oh, get the new vesion it is fixed in that one!
