### ISSUE TITLE
deafult crafting recipe doesnt work

### ISSUE THREAD

**Issue by oofboi44** [IkeVoodoo/LSSMP#30]
the default recipe doesn't work, 
ODO
D  D
ODO
nothing comes up when i try to craft it

**Comment by Anay5499** [comment]
you have to be on thr 1.6 version of the plugin

**Comment by IkeVoodoo** [comment]
^

**Comment by oofboi44** [comment]
i am, i am using 1.6.3, also, i am using another plugin that adds a bunch of custom items, but i dont know if there is any texturepacks. will that conflict with the plugin? also, thanks for replying!

**Comment by IkeVoodoo** [comment]
No, it will not conflict, also O is Obsidian and D is diamond block, just a heads up!
