### ISSUE TITLE
I cant rejoin to get revived

### ISSUE THREAD

**Issue by JimmySheeman** [IkeVoodoo/LSSMP#32]

**Comment by IkeVoodoo** [comment]
May you provide some detail?

**Comment by JacksonJukes** [comment]
He is on my server, what happened was when he died it was to fall damage so now when we want to revive him by using the attribute command to give him a few hearts it doesn't work since he can't join because "your killer is not online"

**Comment by IkeVoodoo** [comment]
He was eliminated, use /lsrevive (playername)
