### ISSUE TITLE
it doesnt ban the player when they lose all of their hearts.

### ISSUE THREAD

**Issue by BaileyB23** [IkeVoodoo/LSSMP#33]
for some reason im testing on my friend to test if the plugin fully works to make an smp just for me and my friends and its a lifesteal smp ( of course ) and ive killed my friend like 20 times by now and hes not banned when he loses all of his hearts, does anyone know how to fix this?

**Comment by IkeVoodoo** [comment]
Can you tell me what happens? Also send me the console logs so i can get more info!

**Comment by BaileyB23** [comment]
basically after i kill the player 10 times they just stay at half a heart. ive even tried killing them more then 10 times to test it. and- idk how to do that, if you'd like telling me then that would be awesome, thanks

**Comment by BaileyB23** [comment]
by "and- idk how to do that" i mean checking the logs, not killing the player more then 10 times lmao

**Comment by IkeVoodoo** [comment]
hm, ill have to fix that!

**Comment by BaileyB23** [comment]
thank you

**Comment by BaileyB23** [comment]
also, when will you be able to fix it?

**Comment by IkeVoodoo** [comment]
I gotta do testing n stuff, ill fix it today probs

**Comment by IkeVoodoo** [comment]
Fixed it today, forgot to say!
