### ISSUE TITLE
What is the config.yml script for losing or gaining hearts only if we kill or be killed by a player.

### ISSUE THREAD

**Issue by ScientiScabi** [IkeVoodoo/LSSMP#34]
What is the config.yml script for losing or gaining hearts only if we kill or be killed by a player.

PLS tell.
![Screenshot 2021-08-22 20 07 24](https://user-images.githubusercontent.com/89345164/130359360-a8192e93-dc77-48e0-bd57-0466cb040bf8.png)

**Comment by IkeVoodoo** [comment]
Last option

**Comment by ScientiScabi** [comment]
> Last option

WDYM should we make the last argument


"enviroinmentStealsHearts": True or False

**Comment by IkeVoodoo** [comment]
False

**Comment by ScientiScabi** [comment]
ok THANKS
