### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by KrypticMZ** [IkeVoodoo/LSSMP#44]
When you restart or reload the server, the config.yml gets reset. Unless I am being completely stupid.

**Comment by IkeVoodoo** [comment]
The config.yml should not be resetting, make sure you have the latest version, also to update the config.yml do /lsreload

**Comment by KrypticMZ** [comment]
Nothing is put in console all that happens is that when I restart or /rl confirm the config resets.

**Comment by IkeVoodoo** [comment]
do not use /rl confirm, that is bound to break things, use /lsreload to reload only the plugin's config and recipes, if it works great, otherwise i have no clue what you have done

**Comment by KrypticMZ** [comment]
Okay thanks
