### ISSUE TITLE
Lifesteal and multiverse

### ISSUE THREAD

**Issue by JayGoBrrr** [IkeVoodoo/LSSMP#46]
Would there be any way for me to either seperate lifesteal between worlds. Or disable it on certain worlds. As I have a pvp world and a SMP world and would like it not to affect the smp when someone dies in the pvp world.

**Comment by IkeVoodoo** [comment]
Adding it to my todo list! Gonna try to release an update asap, might make a trello as well

**Comment by JayGoBrrr** [comment]
Ok thats cool. Thanks.

**Comment by IkeVoodoo** [comment]
Should be already done! Just gotta work on some more features and i'll release

**Comment by JayGoBrrr** [comment]
Ok that cool. Again thanks for responding so quickly.

**Comment by JayGoBrrr** [comment]
Has this been resolved?

**Comment by IkeVoodoo** [comment]
> Has this been resolved? And if so will it reset the existing data?

Not yet! I am still working on the new release!
