### ISSUE TITLE
Recipe folder did not appear at all

### ISSUE THREAD

**Issue by JestemKebab** [IkeVoodoo/LSSMP#49]
So yeah i got invited to be a staff member on my friends server i added the plugin, restarted the server, and the folder is just not there at all
![image](https://user-images.githubusercontent.com/77166968/132050441-9d31953d-d53d-4b25-b264-4c9cc4981c1a.png)
![image](https://user-images.githubusercontent.com/77166968/132050477-fbd5d3d2-f028-4dd2-95dc-6e3380fe4566.png)
lshealth does not work at all either. 1.17.1 paper server btw.

**Comment by IkeVoodoo** [comment]
Send me the console logs, thanks!

**Comment by JestemKebab** [comment]
[latest.log](https://github.com/IkeVoodoo/LSSMP/files/7108258/latest.log)

**Comment by IkeVoodoo** [comment]
This is not my issue as far as I am concerned, however try launching the server as administrator because something with IO was not working properly, also get protocol lib since I see one of your plugins is missing it.

**Comment by JestemKebab** [comment]
yeah thanks i guess it's not my server and it's so incredibly messy because it's  being ran by two people with no clue about servers whatsoever

**Comment by JestemKebab** [comment]
like there is an anticheat that bans for having levitation effect and 3 plugins that add the same /fly command
