### ISSUE TITLE
Plugin for 1.16.5 pls

### ISSUE THREAD

**Issue by TheOnlineHero22** [IkeVoodoo/LSSMP#50]
Pls make this plugin capable for 1.16.5 pls

**Comment by IkeVoodoo** [comment]
I am working on it, it's harder than you think!

**Comment by TheOnlineHero22** [comment]
srry

**Comment by TheOnlineHero22** [comment]
can can we make a new recipe without the diamond blocks and the obby

**Comment by TheOnlineHero22** [comment]
like totems and diamonds and gold

**Comment by IkeVoodoo** [comment]
inside the plugins folder there is a folder named "LifeSteal-Smp-Plugin", then inside that folder go to recipes, there should be a .json you can edit

**Comment by TheOnlineHero22** [comment]
i edited it but i need a elytra in the middle how can i do that

**Comment by TheOnlineHero22** [comment]
i need a elytra in middle how can i do that

**Comment by TheOnlineHero22** [comment]
and how can i withdraw a heart for my friends

**Comment by IkeVoodoo** [comment]
Make a new issue, also getting an heart item is going to be added next version!

**Comment by TheOnlineHero22** [comment]
ok
