### ISSUE TITLE
Plugin on minehut not working

### ISSUE THREAD

**Issue by CRKD14** [IkeVoodoo/LSSMP#54]
When I download the 1.6.40 plugin and then go to file manager on my Minehut server and then go to plugins and upload the file and then go in the server and kill someone they don't lose hearts and I don't gain one. Also when I look into the servers latest logs it says this 
![image](https://user-images.githubusercontent.com/90408217/132728103-269c5c22-6d64-4319-9e52-f4d0a14e0979.png)
This seems like it may be the problem but I don't know. I'm not sure but I think someone else had a similar problem.

**Comment by IkeVoodoo** [comment]
Send me your config, it seems to be invalid.

**Comment by CRKD14** [comment]
ok im not sure if this is it, 
![image](https://user-images.githubusercontent.com/90408217/132829734-b10658a6-b377-40fb-a130-531c0b0bd003.png)

**Comment by IkeVoodoo** [comment]
you added a new line in the ban message, remove it

`banMessage: '&cYou hav been banned due to loosing all of your hearts, your last killer was &4%player%'` is correct

**Comment by CRKD14** [comment]
so i remove the:   %c%player% has lost all of its ' ' s hearts and has been banned

**Comment by CRKD14** [comment]
Now it is saying this again.
![image](https://user-images.githubusercontent.com/90408217/132850492-76bb4635-93ac-4378-b98b-a6d6c98942f3.png)
can you tell me if you fixed it last time or what to do if that happens again. when you told me to send you the configs i went into the file manager then plugins and the Lifesteal smp plugin had a white folder behind it now it doesnt bc i had to reset the server because i went into the world before to test it so i got loot and killed somone and it didnt work so i already had loot thats why I reseted it.

**Comment by IkeVoodoo** [comment]
Just delete the config it will recreate it
