### ISSUE TITLE
craft hearts

### ISSUE THREAD

**Issue by Anay5499** [IkeVoodoo/LSSMP#55]
i tried changing the heart recipe {
    "enabled": true,
    "shaped": true,
    "outputAmount": 1,
    "recipe": [
        "ODO",
        "DVD",
        "ODO"
    ],
    "items": {
        "O": {
            "item": "minecraft:gold_block"
        },
        "D": {
            "item": "minecraft:diamond_block"
        },   
            "V": {
            "item": "minecraft:totem_of_undying"
        }
    }
}
i added another letter to add a totem of undying and changed the obsidian to gold blocks instead but it doesnt work can you please send me the code so i can copy and paste it into the recipe file

**Comment by TheOnlineHero22** [comment]
it should be like this ODO if not DVD

**Comment by IkeVoodoo** [comment]
> it should be like this ODO if not DVD
That does not matter,

**Comment by IkeVoodoo** [comment]
`{
   "enabled":true,
   "shaped":true,
   "outputAmount":1,
   "recipe":[
      "ODO",
      "DVD",
      "ODO"
   ],
   "items":{
      "O":{
         "item":"minecraft:gold_block"
      },
      "D":{
         "item":"minecraft:diamond_block"
      },
      "V":{
         "item":"minecraft:totem_of_undying"
      }
   }
}`

Formatted, also you have to do /lsreload!

**Comment by Anay5499** [comment]
okay thank you it worked now
