### ISSUE TITLE
I need a hard heart recipe

### ISSUE THREAD

**Issue by TheOnlineHero22** [IkeVoodoo/LSSMP#56]
I got a hard recipe but i need to put a elytra in the middle how can i do that

**Comment by IkeVoodoo** [comment]
A recipe editor is propably coming soon

**Comment by RhysyPiece360** [comment]
i could see that but i think that would require a texture pack or a Server side/client side mod for it to work well.

**Comment by IkeVoodoo** [comment]
> i could see that but i think that would require a texture pack or a Server side/client side mod for it to work well.

It wouldn't, as I can make it using plugins (A menu where you select items) it would work with only the plugin installed!
