### ISSUE TITLE
plugin does not work on minehut

### ISSUE THREAD

**Issue by TheGreatPig** [IkeVoodoo/LSSMP#57]
The plugin isn't working because of this error in the logs.
![error](https://user-images.githubusercontent.com/82205253/132852712-17503194-9577-40b7-96c6-6e3839fc4481.png)

**Comment by CRKD14** [comment]
That happend to me to

**Comment by IkeVoodoo** [comment]
Use 1.17-1.17.1, 1.16.5 support is coming next version
