### ISSUE TITLE
Lack of options

### ISSUE THREAD

**Issue by sebastiaannnn** [IkeVoodoo/LSSMP#62]
Where are all the options llike ban for X amount of time etc?
Maybe add this and make a discord server for support

**Comment by IkeVoodoo** [comment]
Both are great ideas!

I am working on customization and yes I will open a discord server.

**Comment by sebastiaannnn** [comment]
Could you dm me on discord? Sebastiaan#7350
im planning to use this on my quite big server (almost 2k members) but before i do that i wanna have like contact so i know bugs can be solved quickly

**Comment by IkeVoodoo** [comment]
Alr

**Comment by sebastiaannnn** [comment]
i don't see a dm

**Comment by IkeVoodoo** [comment]
> i don't see a dm

I added you as a friend, you can't directly message people like that

**Comment by sebastiaannnn** [comment]
Oh eh i have 100+ requests whats your username?

**Comment by IkeVoodoo** [comment]
Ike#2932
