### ISSUE TITLE
Plugin isnt working in minehut

### ISSUE THREAD

**Issue by Noob1234Notreincosmichero02** [IkeVoodoo/LSSMP#65]
Everytime I put the plugin in minehut there is a command that says error how to fix?

**Comment by IkeVoodoo** [comment]
Send me console logs.

**Comment by Noob1234Notreincosmichero02** [comment]
![image](https://user-images.githubusercontent.com/90665589/133605639-63c795d2-6cd3-4846-a6c7-2d1d111f7a13.png)

**Comment by Noob1234Notreincosmichero02** [comment]
![image](https://user-images.githubusercontent.com/90665589/133605762-4fdad063-52c6-4058-90ea-b143d11fa37e.png)

**Comment by Noob1234Notreincosmichero02** [comment]
![image](https://user-images.githubusercontent.com/90665589/133605811-061d4226-ac84-43a8-ad71-a4cab17c3fd1.png)

**Comment by Noob1234Notreincosmichero02** [comment]
I think thats all that is red

**Comment by Noob1234Notreincosmichero02** [comment]
PLEASE RESPOND ASAP

**Comment by IkeVoodoo** [comment]
You know that's not a problem right? Just ignore it, its the plugin telling you "Hey, update servers are down can't update"

**Comment by Noob1234Notreincosmichero02** [comment]
Idk if this is party of it but yeah
![image](https://user-images.githubusercontent.com/90665589/133704272-3a31494e-a750-43c6-a878-28228a8cb491.png)

**Comment by Noob1234Notreincosmichero02** [comment]
Then why doesen't it work on the server

**Comment by Noob1234Notreincosmichero02** [comment]
if u know anything about combatlogx here
![image](https://user-images.githubusercontent.com/90665589/133704449-8d6d4b17-0e5a-4dc6-9d70-482eb7a6a121.png)

**Comment by Noob1234Notreincosmichero02** [comment]
idk what it means

**Comment by Noob1234Notreincosmichero02** [comment]
I also dont know how to update
Im not close to a programmer not planning to be one

**Comment by IkeVoodoo** [comment]
> if u know anything about combatlogx here
> ![image](https://user-images.githubusercontent.com/90665589/133704449-8d6d4b17-0e5a-4dc6-9d70-482eb7a6a121.png)

This is not a problem of my plugin, I will help you this time but don't ask  here for things unrelated

basically you are missing SirBlobmanCore plugin

oh and also, to update just download the plugin again xD, workin on auto updater (it should tell you in mc if it has to update)

**Comment by Noob1234Notreincosmichero02** [comment]
Imma just give up lol
