### ISSUE TITLE
Hearts being lost by entities other than players aswell?

### ISSUE THREAD

**Issue by ZAbstract** [IkeVoodoo/LSSMP#7]
I have no idea how this is happening. I have the plugin .jar file in the plugins folder (multiplayer server) and suddenly when my friend gets killed by a entity (to be specific: a zombie) he loses a heart for no reason. He is on 9 hearts now and I also have no idea how to even give hearts to a player aswell.

I've also downloaded the recent version already.

Console logs:

[11:58:26 ERROR]: Could not pass event PlayerDeathEvent to Lifesteal-Smp-Plugin v1.5.2.0

**Comment by ZAbstract** [comment]
Nevermind found out how to give hearts, but this bug is a really bad issue.

**Comment by ZAbstract** [comment]
And I just figured out why it doesn't work, And its intended
Just saying that the lifesteal smp only makes you lose hearts from players, not entities

**Comment by IkeVoodoo** [comment]
Hello, yes right now it is indeed a bug, it will be fixed with release 1.6, there should be an option in the config, try to see if that works! (If it does not you'll  have to wait for 1.6 to come around)
