### ISSUE TITLE
I made an SMP and everyone who dies to mobs loose a heart

### ISSUE THREAD

**Issue by EricGman007** [IkeVoodoo/LSSMP#8]
Is there a way to fix this in the config? or something. Its so annoying

**Comment by ZAbstract** [comment]
same thing with me.
try give back hearts with this command (Sets the health)

/attribute {player name} generic.max_health base set {amount of half hearts} 
(remove the {})

**Comment by ZAbstract** [comment]
![image](https://user-images.githubusercontent.com/87998308/128602134-f82d6eb2-e376-4881-9bf9-de5c6b1fcf05.png)

**Comment by EricGman007** [comment]
ZAbstract thank you

**Comment by IkeVoodoo** [comment]
Yeah ZAbstract got it, sorry for late replies have been busy recently

**Comment by 3ricbae** [comment]
is there any way to get in contact with you?

**Comment by IkeVoodoo** [comment]
> is there any way to get in contact with you?

Ike#2932 on discord
