### ISSUE TITLE
SPAM - Checking for update

### ISSUE THREAD

**Issue by Teslicek** [IkeVoodoo/LSSMP#82]
![IMG_20211001_111408](https://user-images.githubusercontent.com/87967222/135596015-9e08512c-b651-43b9-a4d8-da940940348d.jpg)

This keeps spamming my console and I have no idea how to stop it. 

I suggest that you check for updates either every hour or once on server startup, because the servers are never online. xD

**Comment by IkeVoodoo** [comment]
Yeah I know, i am fixing it next version
