### ISSUE TITLE
Suggestion: Varied health scaling

### ISSUE THREAD

**Issue by N3xt01** [IkeVoodoo/LSSMP#84]
I think it would be cool if this plugin would be capable of having varied applicable values of health scaling, for example when you die on environment (suffocation, fall damage, lava...), you lose only 0.5hp. However, if you get killed by a player, you lose 1 heart. Would this actually be possible to add? Thank you.

Something like this:
environmentHealthScale: 0.5
playerHealthScale: 1

**Comment by IkeVoodoo** [comment]
Yes this would be possible, adding on my todo list
