### ISSUE TITLE
Can i add this heart withdraw plugin in to the lifesteal plugin?

### ISSUE THREAD

**Issue by highpeakrl** [IkeVoodoo/LSSMP#86]
Is there a way to change it a little so it works with the lifesteal plugin?

[WithdrawCommand.zip](https://github.com/IkeVoodoo/LSSMP/files/7274487/WithdrawCommand.zip)

**Comment by IkeVoodoo** [comment]
Yes, the lifesteal plugin is meant to be as compatible as possible with other plugins, that said you only have to change their max health for it to work with it!

**Comment by highpeakrl** [comment]
So I don't have to change anything else?

**Comment by highpeakrl** [comment]
Not even the Package?

**Comment by highpeakrl** [comment]
What do you mean, am not remaking the command just trying to add a withdraw plugin so players can withdraw hearts.

**Comment by IkeVoodoo** [comment]
oh! /lswithdraw is coming in 1.6.5, tought i already released it
