### ISSUE TITLE
Lifesteal Plugin not working

### ISSUE THREAD

**Issue by Orange128** [IkeVoodoo/LSSMP#9]
So i put it into my smp and its not working. Idk if this is related but im using shockbyte server hosting.

**Comment by ZAbstract** [comment]
make sure to use paperspigot

**Comment by IkeVoodoo** [comment]
> make sure to use paperspigot

This, also I have had reports from about shockbyte but I really don't know what's causing them, anyways the plugin will also move to spigot as well when ver 1.6 comes around, sorry about the problems!
