### ISSUE TITLE
How Do I Make Max Heath

### ISSUE THREAD

**Issue by MrPoggies** [IkeVoodoo/LSSMP#90]
how Do I Create A Maximum Heath to prevent from happening.
![image0](https://user-images.githubusercontent.com/78673189/136478338-1462c9e2-4758-4a5f-ad3e-9757bd1c7256.jpg)

**Comment by MrPoggies** [comment]
please
@IkeVoodoo2 @IkeVoodoo

**Comment by MrPoggies** [comment]
i need to make it so there is a cap to how many hearts u can have

**Comment by IkeVoodoo** [comment]
Version 1.6.5 is bringing that.

**Comment by MrPoggies** [comment]
> Version 1.6.5 is bringing that.

when will that be?
