### ISSUE TITLE
Version 1.16.5

### ISSUE THREAD

**Issue by CHEESY-OP** [IkeVoodoo/LSSMP#93]
I want this plugin for my server which is in version 1.16.5, please accept my request and make this plugin available for 1.16.5!

**Comment by IkeVoodoo** [comment]
I just implemented in experimental version of 1.6.5! (Ironic, I know), Fixing some bugs and Ill release it!

**Comment by Wuzz1** [comment]
what are the bugs?

**Comment by IkeVoodoo** [comment]
Eliminations not working correctly, got to work a bit on translations, and also i have to add custom model data to the heart so you can customize it
