### ISSUE TITLE
Is there a way to modify it?

### ISSUE THREAD

**Issue by LordMagni** [IkeVoodoo/LSSMP#95]
I really like the plugin, but i am wondering: Can i make it so that you also loose hearts when you die from non-player kills?

So like if i get killed by a zombie, i loose a heart, and it just goes to no one

**Comment by LordMagni** [comment]
> Yes, option: environmentStealsHearts in config

I did that but i drowned and didnt loose a heart. My friend drowned and didnt loose a heart

**Comment by IkeVoodoo** [comment]
send your config
